"""Prompt templates module"""
from .summary_prompts import SUMMARY_SYSTEM_PROMPT, SUMMARY_USER_PROMPT
from .risk_prompts import RISK_SYSTEM_PROMPT, RISK_USER_PROMPT
from .chat_prompts import CHAT_SYSTEM_PROMPT, CHAT_USER_PROMPT
from .financial_prompts import FINANCIAL_SYSTEM_PROMPT, FINANCIAL_USER_PROMPT
from .translation_prompts import TRANSLATION_SYSTEM_PROMPT, TRANSLATION_USER_PROMPT

__all__ = [
    "SUMMARY_SYSTEM_PROMPT",
    "SUMMARY_USER_PROMPT",
    "RISK_SYSTEM_PROMPT",
    "RISK_USER_PROMPT",
    "CHAT_SYSTEM_PROMPT",
    "CHAT_USER_PROMPT",
    "FINANCIAL_SYSTEM_PROMPT",
    "FINANCIAL_USER_PROMPT",
    "TRANSLATION_SYSTEM_PROMPT",
    "TRANSLATION_USER_PROMPT"
]
